/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DB4o.Ventanas;

import DB4o. Clases.Pelicula;
import DB4o.Conexion.Conexion;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author morfe
 */
public class AMB extends javax.swing.JFrame {

    private JPanel contentPane;
    private static String salaPeliEmpleado;

    /**
     * Creates new form Porseaka
     */
    public AMB(String queMeLLega) {
        initComponents();
        this.salaPeliEmpleado = queMeLLega;
        System.out.println(salaPeliEmpleado);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonClear = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelAnyo = new javax.swing.JLabel();
        labelDirector = new javax.swing.JLabel();
        labelAP = new javax.swing.JLabel();
        labelAS = new javax.swing.JLabel();
        labelDuracion = new javax.swing.JLabel();
        textoID = new javax.swing.JTextField();
        textoTitulo = new javax.swing.JTextField();
        textoAnyo = new javax.swing.JTextField();
        textoAcPr = new javax.swing.JTextField();
        textoDirector = new javax.swing.JTextField();
        textoDuracion = new javax.swing.JTextField();
        textoAcSe = new javax.swing.JTextField();
        textoErrores = new javax.swing.JTextField();
        textoTrailer = new javax.swing.JTextField();
        lableTrailer = new javax.swing.JLabel();
        labelTituloVentana = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonGuardar.setText("Añadir");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        btnBuscar.setText("Buscar / Mostrar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        botonModificar.setText("Modificar");
        getContentPane().add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 780, -1, -1));

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 780, -1, -1));

        botonClear.setText("Limpiar");
        botonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClearActionPerformed(evt);
            }
        });
        getContentPane().add(botonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        labelID.setForeground(new java.awt.Color(255, 0, 0));
        labelID.setText("ID Pelicula:");
        getContentPane().add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        labelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        labelTitulo.setText("Título:");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        labelAnyo.setForeground(new java.awt.Color(255, 0, 0));
        labelAnyo.setText("Año:");
        getContentPane().add(labelAnyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        labelDirector.setForeground(new java.awt.Color(255, 0, 0));
        labelDirector.setText("Director:");
        getContentPane().add(labelDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        labelAP.setForeground(new java.awt.Color(255, 0, 0));
        labelAP.setText("Actor Principal");
        getContentPane().add(labelAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        labelAS.setForeground(new java.awt.Color(255, 0, 0));
        labelAS.setText("Actor Secundario");
        getContentPane().add(labelAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        labelDuracion.setForeground(new java.awt.Color(255, 0, 0));
        labelDuracion.setText("Duración en minutos:");
        getContentPane().add(labelDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        getContentPane().add(textoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 390, -1));
        getContentPane().add(textoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 390, -1));
        getContentPane().add(textoAnyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 390, -1));
        getContentPane().add(textoAcPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 390, -1));
        getContentPane().add(textoDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 390, -1));
        getContentPane().add(textoDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 390, -1));
        getContentPane().add(textoAcSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 390, -1));
        getContentPane().add(textoErrores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 550, -1));
        getContentPane().add(textoTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 390, -1));

        lableTrailer.setForeground(new java.awt.Color(255, 0, 0));
        lableTrailer.setText("Trailer:");
        getContentPane().add(lableTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        labelTituloVentana.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        labelTituloVentana.setForeground(new java.awt.Color(255, 0, 0));
        labelTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloVentana.setText("PELÍCULAS");
        labelTituloVentana.setToolTipText("");
        getContentPane().add(labelTituloVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, 550, 80));

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 780, -1, -1));

        tablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelicula", "Título", "Año", "Director", "Actor Principal", "Actor Secundario", "Duración", "Trailer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaResultado.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tablaResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 870, 280));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Añadir a;
        switch (salaPeliEmpleado) {
            case "empleado":
                a = new Añadir();
                a.cambiarVentanaEmpleadoss();
                a.show();
                break;
            case "sala":
                a = new Añadir();
                a.cambiarVentanaSalas();
                a.show();
                break;
            case "pelicula":
                a = new Añadir();
                a.cambiarVentanaPelis();
                a.show();
                break;
        }


    }//GEN-LAST:event_botonGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idPelicula = 0;
        if (textoID.getText().isEmpty()) {
            idPelicula = 0;
        } else {
            idPelicula = Integer.parseInt(textoID.getText());
        }
        String titulo = textoTitulo.getText();
        if (titulo.isEmpty()) {
            titulo = null;
        }
        String anyoEstreno = textoAnyo.getText();
        if (anyoEstreno.isEmpty()) {
            anyoEstreno = null;
        }
        String director = textoDirector.getText();
        if (director.isEmpty()) {
            director = null;
        }
        String actorPrinci = textoAcPr.getText();
        if (actorPrinci.isEmpty()) {
            actorPrinci = null;
        }
        String actorSecun = textoAcSe.getText();
        if (actorSecun.isEmpty()) {
            actorSecun = null;
        }
        String duracion = textoDuracion.getText();
        if (duracion.isEmpty()) {
            duracion = null;
        }
        String trailer = textoTrailer.getText();
        if (trailer.isEmpty()) {
            trailer = null;
        }

        Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
        Conexion conexion = new Conexion();
        conexion.buscarPelicula(p1);


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void botonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClearActionPerformed

        textoID.setText("");
        textoTitulo.setText("");
        textoAnyo.setText("");
        textoDirector.setText("");
        textoAcPr.setText("");
        textoAcSe.setText("");
        textoDuracion.setText("");
        textoTrailer.setText("");
        textoErrores.setText("");
    }//GEN-LAST:event_botonClearActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed

        int idPelicula = 0;
        if (textoID.getText().isEmpty()) {
            idPelicula = 0;
        } else {
            idPelicula = Integer.parseInt(textoID.getText());
        }

        String titulo = textoTitulo.getText();
        if (titulo.isEmpty()) {
            titulo = null;
        }
        String anyoEstreno = textoAnyo.getText();
        if (anyoEstreno.isEmpty()) {
            anyoEstreno = null;
        }
        String director = textoDirector.getText();
        if (director == "") {
            director = null;
        }
        String actorPrinci = textoAcPr.getText();
        if (actorPrinci.isEmpty()) {
            actorPrinci = null;
        }
        String actorSecun = textoAcSe.getText();
        if (actorSecun.isEmpty()) {
            actorSecun = null;
        }
        String duracion = textoDuracion.getText();
        if (duracion.isEmpty()) {
            duracion = null;
        }
        String trailer = textoTrailer.getText();
        if (trailer.isEmpty()) {
            trailer = null;
        }

        Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
        Conexion conexion = new Conexion();
        conexion.borrarPelicula(p1);
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.hide();
        Eleccion el = new Eleccion();
        el.show();
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AMB(salaPeliEmpleado).setVisible(true);
            }
        });
    }

    public static void rellenarPelicula(List<Pelicula> pelis) {
        for (int i = 0; i < pelis.size(); i++) {

            tablaResultado.setValueAt(String.valueOf(pelis.get(i).getIdPelicula()), i, 0);
            tablaResultado.setValueAt(pelis.get(i).getTitulo(), i, 1);
            tablaResultado.setValueAt(pelis.get(i).getAnyoEstreno(), i, 2);
            tablaResultado.setValueAt(pelis.get(i).getDirector(), i, 3);
            tablaResultado.setValueAt(pelis.get(i).getActorPrinci(), i, 4);
            tablaResultado.setValueAt(pelis.get(i).getActorSecun(), i, 5);
            tablaResultado.setValueAt(pelis.get(i).getDuracion(), i, 6);
            tablaResultado.setValueAt(pelis.get(i).getTrailer(), i, 7);

        }

    }

    public static void rellenarErrores(String frase) {
        textoErrores.setText(frase);

    }

    public static void cambiarVentanaPelis() {
        labelTituloVentana.setText("PELÍCULAS");
        labelID.setText("ID Pélicula:");
        labelTitulo.setText("Título:");
        labelAnyo.setText("Año: ");
        labelDirector.setText("Director:");
        labelAP.setText("Actor/a principal:");
        labelAS.setText("Actor/a secundario/a:");
        labelDuracion.setText("Duración:");
        lableTrailer.setText("Trailer");
    }

    public static void cambiarVentanaSalas() {
        labelTituloVentana.setText("SALAS");
        labelID.setText("ID Sala:");
        labelTitulo.setText("Capacidad:");
        labelAnyo.setText("Pantalla: ");
        labelDirector.setText("Apertura:");
        labelAP.setText("Horario:");
        labelAS.setText(" ");
        labelDuracion.setText(" ");
        lableTrailer.setText(" ");
        textoAcSe.hide();
        textoDuracion.hide();
        textoTrailer.hide();
    }

    public static void cambiarVentanaEmpleadoss() {
        labelTituloVentana.setText("EMPLEADOS");
        labelID.setText("ID Empleado:");
        labelTitulo.setText("Nombre:");
        labelAnyo.setText("Primer apellido: ");
        labelDirector.setText("Segundo apellido:");
        labelAP.setText("Fecha de Nacimiento:");
        labelAS.setText("Fecha de contratación:");
        labelDuracion.setText("Fecha Fin de Contrato:");
        lableTrailer.setText("Nacionalidad: ");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonClear;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelAP;
    public static javax.swing.JLabel labelAS;
    public static javax.swing.JLabel labelAnyo;
    public static javax.swing.JLabel labelDirector;
    public static javax.swing.JLabel labelDuracion;
    public static javax.swing.JLabel labelID;
    public static javax.swing.JLabel labelTitulo;
    public static javax.swing.JLabel labelTituloVentana;
    public static javax.swing.JLabel lableTrailer;
    public static javax.swing.JTable tablaResultado;
    private static javax.swing.JTextField textoAcPr;
    private static javax.swing.JTextField textoAcSe;
    private static javax.swing.JTextField textoAnyo;
    private static javax.swing.JTextField textoDirector;
    private static javax.swing.JTextField textoDuracion;
    public static javax.swing.JTextField textoErrores;
    private static javax.swing.JTextField textoID;
    private static javax.swing.JTextField textoTitulo;
    private static javax.swing.JTextField textoTrailer;
    // End of variables declaration//GEN-END:variables
}
