/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DB4o.Ventanas;

import DB4o.Clases.Empleado;
import DB4o.Clases.Historico;
import DB4o.Clases.Pelicula;
import DB4o.Clases.Sala;
import DB4o.Conexion.Conexion;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author morfe
 */
public class AñadirHistorico extends javax.swing.JFrame {

    List<Pelicula> peliculas = new ArrayList();
    List<Empleado> empleados = new ArrayList();
    List<Sala> salas = new ArrayList();
    public static Historico histoOriginal;
    List<String> titulosPeliculas = new ArrayList();
    List<Empleado> nombresEmpleados = new ArrayList();

    List<Integer> idSalas = new ArrayList();

    /**
     * Creates new form AñadirHistorico
     */
    public AñadirHistorico() {
        initComponents();
        peliculas = (new Conexion()).mostrarTodasPeliculas();
        empleados = (new Conexion()).mostrarTodosEmpleados();
        salas = (new Conexion()).mostrarTodasSalas();
        int contador1 = 0;
        int contador2 = 0;
        int contador3 = 0;
        for (Pelicula p : peliculas) {
            titulosPeliculas.add(p.getTitulo());
            comboPeli.insertItemAt(p.getTitulo(), contador1);
            contador1++;
        }

        for (Empleado e : empleados) {

            Empleado emple = new Empleado(0, e.getNombre(), e.getApellido1(), e.getApellido2(), null, null, null, null, null);
            nombresEmpleados.add(contador2, emple);
            comboEmpleado.insertItemAt(e.getNombre() + " " + e.getApellido1() + " " + e.getApellido2(), contador2);
            contador2++;

        }

        for (Sala s : salas) {
            idSalas.add(s.getIdSala());
            comboSala.insertItemAt(String.valueOf(s.getIdSala()), contador3);
            contador3++;
        }

    }

    public Empleado buscarEseEmpleado(Empleado e) {
        Conexion conexion = new Conexion();
        Empleado prov = conexion.buscarEseEmpleado(e);

        return prov;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelEmpleado = new javax.swing.JLabel();
        labelSala = new javax.swing.JLabel();
        labelPeli = new javax.swing.JLabel();
        labelFechaEmision = new javax.swing.JLabel();
        comboSala = new javax.swing.JComboBox<>();
        comboPeli = new javax.swing.JComboBox<>();
        comboEmpleado = new javax.swing.JComboBox<>();
        botonAñadir = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        comboHora = new javax.swing.JComboBox<>();
        labelHora = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        textoFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrado"));

        labelEmpleado.setForeground(new java.awt.Color(255, 0, 0));
        labelEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmpleado.setText("Empleado:");

        labelSala.setForeground(new java.awt.Color(255, 0, 0));
        labelSala.setText("Sala:");

        labelPeli.setForeground(new java.awt.Color(255, 0, 0));
        labelPeli.setText("Peli:");

        labelFechaEmision.setForeground(new java.awt.Color(255, 0, 0));
        labelFechaEmision.setText("Fecha de emisión (dd/mm/aaaa):");

        comboSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalaActionPerformed(evt);
            }
        });

        comboPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPeliActionPerformed(evt);
            }
        });

        comboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpleadoActionPerformed(evt);
            }
        });

        botonAñadir.setText("Añadir Histórico");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar");

        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "17:30-19:30", "20:00-22:00", "22:30-00:30" }));
        comboHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHoraActionPerformed(evt);
            }
        });

        labelHora.setForeground(new java.awt.Color(255, 0, 0));
        labelHora.setText("Hora de emisión:");

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboHora, 0, 146, Short.MAX_VALUE)
                        .addGap(339, 339, 339)
                        .addComponent(botonAñadir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboSala, 0, 146, Short.MAX_VALUE)
                                    .addComponent(comboEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(207, 207, 207)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoFecha)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmpleado))
                                .addGap(296, 296, 296)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFechaEmision)
                                    .addComponent(labelPeli))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAtras)
                    .addComponent(botonLimpiar))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(labelPeli))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(comboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaEmision)
                    .addComponent(labelSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(labelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAñadir)
                            .addComponent(botonLimpiar))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSalaActionPerformed

    private void comboPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPeliActionPerformed

    private void comboEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpleadoActionPerformed

    }//GEN-LAST:event_comboEmpleadoActionPerformed

    private void comboHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHoraActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed

        if (botonAñadir.getText() == "Añadir") {
            int empleado = comboEmpleado.getSelectedIndex();

            Conexion conexion = new Conexion();
            Empleado empleadoAVincular = buscarEseEmpleado(nombresEmpleados.get(empleado));//Aqui ya esta el Empleado entero para poder ser vinculado

            int sala = Integer.parseInt((String) comboSala.getSelectedItem());
            Sala sa = new Sala(sala, 0, 0, null, null);
            Sala salaAVincular = conexion.buscarEsaSala(sa);

            String pelicula = (String) comboPeli.getSelectedItem();
            Pelicula pe = new Pelicula(0, pelicula, null, null, null, null, null, null);
            Pelicula peliAVincular = conexion.buscarEsaPelicula(pe);

            String fecha = textoFecha.getText();
            String hora = (String) comboHora.getSelectedItem();

            Historico historico = new Historico(fecha, hora, salaAVincular, empleadoAVincular, peliAVincular);
            conexion.guardarHistorico(historico);
            this.hide();
        }else{
           //TODO
            //conexion.modificarHistorico(null,null);
            this.hide();
        }


    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.hide();
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAtras;
    public javax.swing.JButton botonAñadir;
    public javax.swing.JButton botonLimpiar;
    public javax.swing.JComboBox<String> comboEmpleado;
    public javax.swing.JComboBox<String> comboHora;
    public javax.swing.JComboBox<String> comboPeli;
    public javax.swing.JComboBox<String> comboSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelFechaEmision;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelPeli;
    private javax.swing.JLabel labelSala;
    public javax.swing.JTextField textoFecha;
    // End of variables declaration//GEN-END:variables
}
