/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DB4o.Ventanas;

import DB4o.Clases.Empleado;
import DB4o.Clases.Pelicula;
import DB4o.Clases.Sala;
import DB4o.Conexion.Conexion;
import static DB4o.Ventanas.AMB.labelTituloVentana;
import static DB4o.Ventanas.AMB.tablaResultado;
import static DB4o.Ventanas.VentanaAñadir.salaPeliEmpleado;

public class VentanaAñadir2 extends javax.swing.JFrame {
    public static Pelicula peliOriginal;
    public static Empleado empleOriginal;
    public static Sala salaOriginal;
    public static String salaPeliEmpleado;
    public static AMB amb;
    /**
     * Creates new form VentanaAñadir2
     */
    public VentanaAñadir2(String queMeLLega) {
        initComponents();
        this.salaPeliEmpleado = queMeLLega;
        System.out.println(salaPeliEmpleado);

    }

    
     public static void cambiarVentanaPelis() {
        labelTituloVentana.setText("PELÍCULAS");
        labelID.setText("ID Pélicula:");
        labelTitulo.setText("Título:");
        labelAnyo.setText("Año: ");
        labelDirector.setText("Director:");
        labelAP.setText("Actor/a principal:");
        labelAS.setText("Actor/a secundario/a:");
        labelDuracion.setText("Duración:");
        labelTrailer.setText("Trailer");
        labelCargo.hide();
        textoCargo.hide();
    }

    public static void cambiarVentanaSalas() {
        labelTituloVentana.setText("SALAS");
        labelID.setText("ID Sala:");
        labelTitulo.setText("Capacidad:");
        labelAnyo.setText("Pantalla: ");
        labelDirector.setText("Apertura:");
        labelAP.setText("Horario:");
        labelAS.setText(" ");
        labelDuracion.setText(" ");
        labelTrailer.setText(" ");
        textoAcSe.hide();
        textoDuracion.hide();
        textoTrailer.hide();
        labelCargo.hide();
        textoCargo.hide();
    }

    public static void cambiarVentanaEmpleadoss() {
        labelTituloVentana.setText("EMPLEADOS");
        labelID.setText("ID Empleado:");
        labelTitulo.setText("Nombre:");
        labelAnyo.setText("Primer apellido: ");
        labelDirector.setText("Segundo apellido:");
        labelAP.setText("Fecha de Nacimiento:");
        labelAS.setText("Fecha de contratación:");
        labelDuracion.setText("Fecha Fin de Contrato:");
        labelTrailer.setText("Nacionalidad: ");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAtras = new javax.swing.JButton();
        botonAñadir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        textoID = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JTextField();
        labelAnyo = new javax.swing.JLabel();
        textoAnyo = new javax.swing.JTextField();
        labelDirector = new javax.swing.JLabel();
        textoDirector = new javax.swing.JTextField();
        labelAP = new javax.swing.JLabel();
        labelAS = new javax.swing.JLabel();
        textoAcPr = new javax.swing.JTextField();
        textoAcSe = new javax.swing.JTextField();
        labelDuracion = new javax.swing.JLabel();
        textoDuracion = new javax.swing.JTextField();
        labelTrailer = new javax.swing.JLabel();
        textoTrailer = new javax.swing.JTextField();
        labelCargo = new javax.swing.JLabel();
        textoCargo = new javax.swing.JTextField();
        botonAtras1 = new javax.swing.JButton();
        botonAñadir1 = new javax.swing.JButton();

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelID.setForeground(new java.awt.Color(255, 0, 0));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setText("ID Pelicula:");

        labelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Título:");

        textoTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTituloKeyTyped(evt);
            }
        });

        labelAnyo.setForeground(new java.awt.Color(255, 0, 0));
        labelAnyo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAnyo.setText("Año:");

        labelDirector.setForeground(new java.awt.Color(255, 0, 0));
        labelDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDirector.setText("Director:");

        labelAP.setForeground(new java.awt.Color(255, 0, 0));
        labelAP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAP.setText("Actor Principal");

        labelAS.setForeground(new java.awt.Color(255, 0, 0));
        labelAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAS.setText("Actor Secundario");

        labelDuracion.setForeground(new java.awt.Color(255, 0, 0));
        labelDuracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDuracion.setText("Duración en minutos:");

        labelTrailer.setForeground(new java.awt.Color(255, 0, 0));
        labelTrailer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTrailer.setText("Trailer:");

        labelCargo.setForeground(new java.awt.Color(255, 0, 0));
        labelCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCargo.setText("Trailer:");

        textoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCargoActionPerformed(evt);
            }
        });

        botonAtras1.setText("Atrás");
        botonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras1ActionPerformed(evt);
            }
        });

        botonAñadir1.setText("Añadir");
        botonAñadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoAcPr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoAcSe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonAñadir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 490, Short.MAX_VALUE)
                .addComponent(botonAtras1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnyo)
                    .addComponent(textoAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDirector)
                    .addComponent(textoDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAP)
                    .addComponent(textoAcPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAS)
                    .addComponent(textoAcSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracion)
                    .addComponent(textoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTrailer)
                    .addComponent(textoTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargo)
                    .addComponent(textoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(botonAñadir1)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtras1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTituloKeyTyped
        /*if(Añadir.labelTitulo.getText()=="Capacidad:"){
            char enter=evt.getKeyChar();
            if(!(Character.isDigit(enter))){
                evt.consume();
            }
        }*/
    }//GEN-LAST:event_textoTituloKeyTyped

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.hide();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed

        switch (salaPeliEmpleado) {
            case "empleado":
            if (botonAñadir.getText() == "Añadir") {
                int idEmpleado = Integer.parseInt(textoID.getText());
                String nombre = textoTitulo.getText();
                String ape1 = textoAnyo.getText();
                String ape2 = textoDirector.getText();
                String fnac = textoAcPr.getText();
                String fcontra = textoAcSe.getText();
                String ffin = textoDuracion.getText();
                String nacionalidad = textoTrailer.getText();
                String cargo = textoCargo.getText();

                Empleado e1 = new Empleado(idEmpleado, nombre, ape1, ape2, fnac, fcontra, ffin, nacionalidad, cargo);
                Conexion conexion = new Conexion();
                conexion.guardarEmpleado(e1);
                this.hide();
            } else {
                int idEmpleado = Integer.parseInt(textoID.getText());
                String nombre = textoTitulo.getText();
                String ape1 = textoAnyo.getText();
                String ape2 = textoDirector.getText();
                String fnac = textoAcPr.getText();
                String fcontra = textoAcSe.getText();
                String ffin = textoDuracion.getText();
                String nacionalidad = textoTrailer.getText();
                String cargo = textoCargo.getText();

                Empleado e1 = new Empleado(idEmpleado, nombre, ape1, ape2, fnac, fcontra, ffin, nacionalidad, cargo);
                Conexion conexion = new Conexion();
                conexion.modificarEmpleado(empleOriginal, e1);
                for (int i = 0; i < amb.tablaResultadoEmpleados.getRowCount(); i++) {

                    amb.tablaResultadoEmpleados.setValueAt("", i, 0);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 1);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 2);
                    amb.tablaResultadoEmpleados.setValueAt("", i, 3);
                    amb.tablaResultadoEmpleados.setValueAt("", i, 4);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 5);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 6);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 7);

                }
                this.hide();
            }
            break;
            case "sala":
            if (botonAñadir.getText() == "Añadir") {
                int idSala = Integer.parseInt(textoID.getText());
                int capacidad =  Integer.parseInt(textoTitulo.getText());
                int pantalla =  Integer.parseInt(textoAnyo.getText());
                String apertura = textoDirector.getText();
                String horario = textoAcPr.getText();

                Sala s1 = new Sala(idSala, capacidad, pantalla, apertura, horario);
                Conexion conexion = new Conexion();
                conexion.guardarSala(s1);
                this.hide();
            } else {
                int idSala = Integer.parseInt(textoID.getText());
                int capacidad =  Integer.parseInt(textoTitulo.getText());
                int pantalla =  Integer.parseInt(textoAnyo.getText());
                String apertura = textoDirector.getText();
                String horario = textoAcPr.getText();

                Sala s1 = new Sala(idSala, capacidad, pantalla, apertura, horario);
                Conexion conexion = new Conexion();
                conexion.modificarSala(salaOriginal, s1);
                for (int i = 0; i < amb.tablaResultadoSalas.getRowCount(); i++) {

                    amb.tablaResultadoSalas.setValueAt("", i, 0);
                    amb.tablaResultadoSalas.setValueAt("", i, 1);
                    amb.tablaResultadoSalas.setValueAt("", i, 2);
                    amb.tablaResultadoSalas.setValueAt("", i, 3);
                    amb.tablaResultadoSalas.setValueAt("", i, 4);

                }
                this.hide();
            }
            break;
            case "pelicula":
            if (botonAñadir.getText() == "Añadir") {
                int idPelicula = Integer.parseInt(textoID.getText());
                String titulo = textoTitulo.getText();
                String anyoEstreno = textoAnyo.getText();
                String director = textoDirector.getText();
                String actorPrinci = textoAcPr.getText();
                String actorSecun = textoAcSe.getText();
                String duracion = textoDuracion.getText();
                String trailer = textoTrailer.getText();

                Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
                Conexion conexion = new Conexion();
                conexion.guardarPelicula(p1);
                this.hide();
            } else {
                int idPelicula = Integer.parseInt(textoID.getText());
                String titulo = textoTitulo.getText();
                String anyoEstreno = textoAnyo.getText();
                String director = textoDirector.getText();
                String actorPrinci = textoAcPr.getText();
                String actorSecun = textoAcSe.getText();
                String duracion = textoDuracion.getText();
                String trailer = textoTrailer.getText();

                Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
                Conexion conexion = new Conexion();
                conexion.modificarPelicula(peliOriginal, p1);
                for (int i = 0; i < tablaResultado.getRowCount(); i++) {

                    amb.tablaResultado.setValueAt("", i, 0);
                    amb.tablaResultado.setValueAt("", i, 1);
                    amb.tablaResultado.setValueAt("", i, 2);
                    amb.tablaResultado.setValueAt("", i, 3);
                    amb. tablaResultado.setValueAt("", i, 4);
                    amb.tablaResultado.setValueAt("", i, 5);
                    amb.tablaResultado.setValueAt("", i, 6);
                    amb. tablaResultado.setValueAt("", i, 7);

                }
                this.hide();
            }
            break;
        }

    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras1ActionPerformed
        this.hide();
    }//GEN-LAST:event_botonAtras1ActionPerformed

    private void botonAñadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadir1ActionPerformed

        switch (salaPeliEmpleado) {
            case "empleado":
            if (botonAñadir.getText() == "Añadir") {
                int idEmpleado = Integer.parseInt(textoID.getText());
                String nombre = textoTitulo.getText();
                String ape1 = textoAnyo.getText();
                String ape2 = textoDirector.getText();
                String fnac = textoAcPr.getText();
                String fcontra = textoAcSe.getText();
                String ffin = textoDuracion.getText();
                String nacionalidad = textoTrailer.getText();
                String cargo = textoCargo.getText();

                Empleado e1 = new Empleado(idEmpleado, nombre, ape1, ape2, fnac, fcontra, ffin, nacionalidad, cargo);
                Conexion conexion = new Conexion();
                conexion.guardarEmpleado(e1);
                this.hide();
            } else {
                int idEmpleado = Integer.parseInt(textoID.getText());
                String nombre = textoTitulo.getText();
                String ape1 = textoAnyo.getText();
                String ape2 = textoDirector.getText();
                String fnac = textoAcPr.getText();
                String fcontra = textoAcSe.getText();
                String ffin = textoDuracion.getText();
                String nacionalidad = textoTrailer.getText();
                String cargo = textoCargo.getText();

                Empleado e1 = new Empleado(idEmpleado, nombre, ape1, ape2, fnac, fcontra, ffin, nacionalidad, cargo);
                Conexion conexion = new Conexion();
                conexion.modificarEmpleado(empleOriginal, e1);
                for (int i = 0; i < amb.tablaResultadoEmpleados.getRowCount(); i++) {

                    amb.tablaResultadoEmpleados.setValueAt("", i, 0);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 1);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 2);
                    amb.tablaResultadoEmpleados.setValueAt("", i, 3);
                    amb.tablaResultadoEmpleados.setValueAt("", i, 4);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 5);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 6);
                    amb. tablaResultadoEmpleados.setValueAt("", i, 7);

                }
                this.hide();
            }
            break;
            case "sala":
            if (botonAñadir.getText() == "Añadir") {
                int idSala = Integer.parseInt(textoID.getText());
                int capacidad =  Integer.parseInt(textoTitulo.getText());
                int pantalla =  Integer.parseInt(textoAnyo.getText());
                String apertura = textoDirector.getText();
                String horario = textoAcPr.getText();

                Sala s1 = new Sala(idSala, capacidad, pantalla, apertura, horario);
                Conexion conexion = new Conexion();
                conexion.guardarSala(s1);
                this.hide();
            } else {
                int idSala = Integer.parseInt(textoID.getText());
                int capacidad =  Integer.parseInt(textoTitulo.getText());
                int pantalla =  Integer.parseInt(textoAnyo.getText());
                String apertura = textoDirector.getText();
                String horario = textoAcPr.getText();

                Sala s1 = new Sala(idSala, capacidad, pantalla, apertura, horario);
                Conexion conexion = new Conexion();
                conexion.modificarSala(salaOriginal, s1);
                for (int i = 0; i < amb.tablaResultadoSalas.getRowCount(); i++) {

                    amb.tablaResultadoSalas.setValueAt("", i, 0);
                    amb.tablaResultadoSalas.setValueAt("", i, 1);
                    amb.tablaResultadoSalas.setValueAt("", i, 2);
                    amb.tablaResultadoSalas.setValueAt("", i, 3);
                    amb.tablaResultadoSalas.setValueAt("", i, 4);

                }
                this.hide();
            }
            break;
            case "pelicula":
            if (botonAñadir.getText() == "Añadir") {
                int idPelicula = Integer.parseInt(textoID.getText());
                String titulo = textoTitulo.getText();
                String anyoEstreno = textoAnyo.getText();
                String director = textoDirector.getText();
                String actorPrinci = textoAcPr.getText();
                String actorSecun = textoAcSe.getText();
                String duracion = textoDuracion.getText();
                String trailer = textoTrailer.getText();

                Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
                Conexion conexion = new Conexion();
                conexion.guardarPelicula(p1);
                this.hide();
            } else {
                int idPelicula = Integer.parseInt(textoID.getText());
                String titulo = textoTitulo.getText();
                String anyoEstreno = textoAnyo.getText();
                String director = textoDirector.getText();
                String actorPrinci = textoAcPr.getText();
                String actorSecun = textoAcSe.getText();
                String duracion = textoDuracion.getText();
                String trailer = textoTrailer.getText();

                Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
                Conexion conexion = new Conexion();
                conexion.modificarPelicula(peliOriginal, p1);
                for (int i = 0; i < amb.tablaResultado.getRowCount(); i++) {

                    amb.tablaResultado.setValueAt("", i, 0);
                    amb.tablaResultado.setValueAt("", i, 1);
                    amb.tablaResultado.setValueAt("", i, 2);
                    amb.tablaResultado.setValueAt("", i, 3);
                    amb. tablaResultado.setValueAt("", i, 4);
                    amb.tablaResultado.setValueAt("", i, 5);
                    amb.tablaResultado.setValueAt("", i, 6);
                    amb. tablaResultado.setValueAt("", i, 7);

                }
                this.hide();
            }
            break;
        }

    }//GEN-LAST:event_botonAñadir1ActionPerformed

    private void textoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadir2(salaPeliEmpleado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonAtras1;
    public static javax.swing.JButton botonAñadir;
    public static javax.swing.JButton botonAñadir1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel labelAP;
    public static javax.swing.JLabel labelAS;
    public static javax.swing.JLabel labelAnyo;
    public static javax.swing.JLabel labelCargo;
    public static javax.swing.JLabel labelDirector;
    public static javax.swing.JLabel labelDuracion;
    public static javax.swing.JLabel labelID;
    public static javax.swing.JLabel labelTitulo;
    public static javax.swing.JLabel labelTrailer;
    public static javax.swing.JTextField textoAcPr;
    public static javax.swing.JTextField textoAcSe;
    public static javax.swing.JTextField textoAnyo;
    public static javax.swing.JTextField textoCargo;
    public static javax.swing.JTextField textoDirector;
    public static javax.swing.JTextField textoDuracion;
    public static javax.swing.JTextField textoID;
    public static javax.swing.JTextField textoTitulo;
    public static javax.swing.JTextField textoTrailer;
    // End of variables declaration//GEN-END:variables
}
