/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DB4o.Ventanas;

import DB4o.Clases.Empleado;
import DB4o.Clases.Pelicula;
import DB4o.Clases.Sala;
import DB4o.Conexion.Conexion;
import static DB4o.Ventanas.AMB.labelTituloVentana;
import static DB4o.Ventanas.AMB.tablaResultado;
import static DB4o.Ventanas.AMB.tablaResultadoEmpleados;
import static DB4o.Ventanas.AMB.tablaResultadoSalas;

/**
 *
 * @author 9fdam07
 */
public class VentanaAñadir extends javax.swing.JFrame {

    public static Pelicula peliOriginal;
    public static Empleado empleOriginal;
    public static Sala salaOriginal;
    public static String salaPeliEmpleado;
    public static AMB amb;

    public VentanaAñadir(String queMeLLega) {
        initComponents();
        this.salaPeliEmpleado = queMeLLega;
        System.out.println(salaPeliEmpleado);

    }

    public static void cambiarVentanaPelis() {
        labelTituloVentana.setText("PELÍCULAS");
        labelID.setText("ID Pélicula:");
        labelTitulo.setText("Título:");
        labelAnyo.setText("Año: ");
        labelDirector.setText("Director:");
        labelAP.setText("Actor/a principal:");
        labelAS.setText("Actor/a secundario/a:");
        labelDuracion.setText("Duración:");
        lableTrailer.setText("Trailer");
        labelCargo.hide();
        textoCargo.hide();
    }

    public static void cambiarVentanaSalas() {
        labelTituloVentana.setText("SALAS");
        labelID.setText("ID Sala:");
        labelTitulo.setText("Capacidad:");
        labelAnyo.setText("Pantalla: ");
        labelDirector.setText("Apertura:");
        labelAP.setText("Horario:");
        labelAS.setText(" ");
        labelDuracion.setText(" ");
        lableTrailer.setText(" ");
        textoAcSe.hide();
        textoDuracion.hide();
        textoTrailer.hide();
        labelCargo.hide();
        textoCargo.hide();
    }

    public static void cambiarVentanaEmpleadoss() {
        labelTituloVentana.setText("EMPLEADOS");
        labelID.setText("ID Empleado:");
        labelTitulo.setText("Nombre:");
        labelAnyo.setText("Primer apellido: ");
        labelDirector.setText("Segundo apellido:");
        labelAP.setText("Fecha de Nacimiento:");
        labelAS.setText("Fecha de contratación:");
        labelDuracion.setText("Fecha Fin de Contrato:");
        lableTrailer.setText("Nacionalidad: ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelID = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelAnyo = new javax.swing.JLabel();
        labelDirector = new javax.swing.JLabel();
        labelAP = new javax.swing.JLabel();
        labelAS = new javax.swing.JLabel();
        labelDuracion = new javax.swing.JLabel();
        textoID = new javax.swing.JTextField();
        textoTitulo = new javax.swing.JTextField();
        textoAnyo = new javax.swing.JTextField();
        textoAcPr = new javax.swing.JTextField();
        textoDirector = new javax.swing.JTextField();
        textoDuracion = new javax.swing.JTextField();
        textoAcSe = new javax.swing.JTextField();
        textoTrailer = new javax.swing.JTextField();
        lableTrailer = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        textoCargo = new javax.swing.JTextField();
        labelCargo = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelID.setForeground(new java.awt.Color(255, 0, 0));
        labelID.setText("ID Pelicula:");

        labelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        labelTitulo.setText("Título:");

        labelAnyo.setForeground(new java.awt.Color(255, 0, 0));
        labelAnyo.setText("Año:");

        labelDirector.setForeground(new java.awt.Color(255, 0, 0));
        labelDirector.setText("Director:");

        labelAP.setForeground(new java.awt.Color(255, 0, 0));
        labelAP.setText("Actor Principal");

        labelAS.setForeground(new java.awt.Color(255, 0, 0));
        labelAS.setText("Actor Secundario");

        labelDuracion.setForeground(new java.awt.Color(255, 0, 0));
        labelDuracion.setText("Duración en minutos:");

        lableTrailer.setForeground(new java.awt.Color(255, 0, 0));
        lableTrailer.setText("Trailer:");

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        labelCargo.setForeground(new java.awt.Color(255, 0, 0));
        labelCargo.setText("Cargo:");

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCargo)
                        .addGap(126, 126, 126)
                        .addComponent(textoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonAñadir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                            .addComponent(botonAtras))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelTitulo)
                                    .addGap(130, 130, 130)
                                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelAnyo)
                                    .addGap(137, 137, 137)
                                    .addComponent(textoAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDirector)
                                    .addGap(118, 118, 118)
                                    .addComponent(textoDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelAP)
                                    .addGap(92, 92, 92)
                                    .addComponent(textoAcPr, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelAS)
                                    .addGap(78, 78, 78)
                                    .addComponent(textoAcSe, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDuracion)
                                    .addGap(59, 59, 59)
                                    .addComponent(textoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lableTrailer)
                                    .addGap(126, 126, 126)
                                    .addComponent(textoTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnyo))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDirector))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAcPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAP))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAcSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAS))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuracion))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableTrailer)
                    .addComponent(textoTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCargo)
                    .addComponent(textoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(botonAñadir)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAtras)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed

        switch (salaPeliEmpleado) {
            case "empleado":
                if (botonAñadir.getText() == "Añadir") {
                    int idEmpleado = Integer.parseInt(textoID.getText());
                    String nombre = textoTitulo.getText();
                    String ape1 = textoAnyo.getText();
                    String ape2 = textoDirector.getText();
                    String fnac = textoAcPr.getText();
                    String fcontra = textoAcSe.getText();
                    String ffin = textoDuracion.getText();
                    String nacionalidad = textoTrailer.getText();
                    String cargo = textoCargo.getText();
                    
                    Empleado e1 = new Empleado(idEmpleado, nombre, ape1, ape2, fnac, fcontra, ffin, nacionalidad, cargo);
                    Conexion conexion = new Conexion();
                    conexion.guardarEmpleado(e1);
                    this.hide();
                } else {
                    int idEmpleado = Integer.parseInt(textoID.getText());
                    String nombre = textoTitulo.getText();
                    String ape1 = textoAnyo.getText();
                    String ape2 = textoDirector.getText();
                    String fnac = textoAcPr.getText();
                    String fcontra = textoAcSe.getText();
                    String ffin = textoDuracion.getText();
                    String nacionalidad = textoTrailer.getText();
                    String cargo = textoCargo.getText();
                    
                    Empleado e1 = new Empleado(idEmpleado, nombre, ape1, ape2, fnac, fcontra, ffin, nacionalidad, cargo);
                    Conexion conexion = new Conexion();
                    conexion.modificarEmpleado(empleOriginal, e1);
                    for (int i = 0; i < amb.tablaResultadoEmpleados.getRowCount(); i++) {

                        amb.tablaResultadoEmpleados.setValueAt("", i, 0);
                       amb. tablaResultadoEmpleados.setValueAt("", i, 1);
                       amb. tablaResultadoEmpleados.setValueAt("", i, 2);
                        amb.tablaResultadoEmpleados.setValueAt("", i, 3);
                        amb.tablaResultadoEmpleados.setValueAt("", i, 4);
                       amb. tablaResultadoEmpleados.setValueAt("", i, 5);
                       amb. tablaResultadoEmpleados.setValueAt("", i, 6);
                       amb. tablaResultadoEmpleados.setValueAt("", i, 7);

                    }
                    this.hide();
                }
                break;
            case "sala":
                     if (botonAñadir.getText() == "Añadir") {
                     int idSala = Integer.parseInt(textoID.getText());
                    int capacidad =  Integer.parseInt(textoTitulo.getText());
                    int pantalla =  Integer.parseInt(textoAnyo.getText());
                    String apertura = textoDirector.getText();
                    String horario = textoAcPr.getText();
                   

                    Sala s1 = new Sala(idSala, capacidad, pantalla, apertura, horario);
                    Conexion conexion = new Conexion();
                    conexion.guardarSala(s1);
                    this.hide();
                } else {
                    int idSala = Integer.parseInt(textoID.getText());
                    int capacidad =  Integer.parseInt(textoTitulo.getText());
                    int pantalla =  Integer.parseInt(textoAnyo.getText());
                    String apertura = textoDirector.getText();
                    String horario = textoAcPr.getText();
                   

                    Sala s1 = new Sala(idSala, capacidad, pantalla, apertura, horario);
                    Conexion conexion = new Conexion();
                    conexion.modificarSala(salaOriginal, s1);
                    for (int i = 0; i < amb.tablaResultadoSalas.getRowCount(); i++) {

                        amb.tablaResultadoSalas.setValueAt("", i, 0);
                        amb.tablaResultadoSalas.setValueAt("", i, 1);
                        amb.tablaResultadoSalas.setValueAt("", i, 2);
                        amb.tablaResultadoSalas.setValueAt("", i, 3);
                        amb.tablaResultadoSalas.setValueAt("", i, 4);
                       
                    }
                    this.hide();
                }
                break;
            case "pelicula":
                if (botonAñadir.getText() == "Añadir") {
                    int idPelicula = Integer.parseInt(textoID.getText());
                    String titulo = textoTitulo.getText();
                    String anyoEstreno = textoAnyo.getText();
                    String director = textoDirector.getText();
                    String actorPrinci = textoAcPr.getText();
                    String actorSecun = textoAcSe.getText();
                    String duracion = textoDuracion.getText();
                    String trailer = textoTrailer.getText();

                    Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
                    Conexion conexion = new Conexion();
                    conexion.guardarPelicula(p1);
                    this.hide();
                } else {
                    int idPelicula = Integer.parseInt(textoID.getText());
                    String titulo = textoTitulo.getText();
                    String anyoEstreno = textoAnyo.getText();
                    String director = textoDirector.getText();
                    String actorPrinci = textoAcPr.getText();
                    String actorSecun = textoAcSe.getText();
                    String duracion = textoDuracion.getText();
                    String trailer = textoTrailer.getText();

                    Pelicula p1 = new Pelicula(idPelicula, titulo, anyoEstreno, director, actorPrinci, actorSecun, duracion, trailer);
                    Conexion conexion = new Conexion();
                    conexion.modificarPelicula(peliOriginal, p1);
                    for (int i = 0; i < tablaResultado.getRowCount(); i++) {

                        amb.tablaResultado.setValueAt("", i, 0);
                        amb.tablaResultado.setValueAt("", i, 1);
                        amb.tablaResultado.setValueAt("", i, 2);
                        amb.tablaResultado.setValueAt("", i, 3);
                       amb. tablaResultado.setValueAt("", i, 4);
                        amb.tablaResultado.setValueAt("", i, 5);
                        amb.tablaResultado.setValueAt("", i, 6);
                       amb. tablaResultado.setValueAt("", i, 7);

                    }
                    this.hide();
                }
                break;
        }


    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.hide();
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadir(salaPeliEmpleado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    public static javax.swing.JButton botonAñadir;
    public static javax.swing.JLabel labelAP;
    public static javax.swing.JLabel labelAS;
    public static javax.swing.JLabel labelAnyo;
    public static javax.swing.JLabel labelCargo;
    public static javax.swing.JLabel labelDirector;
    public static javax.swing.JLabel labelDuracion;
    public static javax.swing.JLabel labelID;
    public static javax.swing.JLabel labelTitulo;
    public static javax.swing.JLabel lableTrailer;
    public static javax.swing.JTextField textoAcPr;
    public static javax.swing.JTextField textoAcSe;
    public static javax.swing.JTextField textoAnyo;
    public static javax.swing.JTextField textoCargo;
    public static javax.swing.JTextField textoDirector;
    public static javax.swing.JTextField textoDuracion;
    public static javax.swing.JTextField textoID;
    public static javax.swing.JTextField textoTitulo;
    public static javax.swing.JTextField textoTrailer;
    // End of variables declaration//GEN-END:variables
}
