/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL.Ventanas;

import SQL.Dao.EmpleadoFunciones;
import SQL.Dao.HistoricoFunciones;
import SQL.Dao.PeliculaFunciones;
import SQL.Dao.SalaFunciones;
import java.io.IOException;
import java.nio.file.attribute.AttributeView;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author morfe
 */
public class Eleccion extends javax.swing.JFrame {

    //ventanas
    public Main ventanaMain;
    public AMB ventanaAMB;
    public Historico ventanaHistorico;
    public Metadatos ventanaMetadatos;
    //archivos funciones
    public PeliculaFunciones peliculaFunciones = new PeliculaFunciones();
    public SalaFunciones salaFunciones = new SalaFunciones();
    public EmpleadoFunciones empleadoFunciones = new EmpleadoFunciones();
    public HistoricoFunciones historicoFunciones = new HistoricoFunciones();

    //Si soy ventana MySql o SQlite
    private boolean soyMySql;

    /**
     * Creates new form Eleccion
     */
    public Eleccion() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonSalas = new javax.swing.JButton();
        botonEmpleado = new javax.swing.JButton();
        botonHistorico = new javax.swing.JButton();
        botonPelis = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        botonMetadato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Magneto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido!");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        botonSalas.setFont(new java.awt.Font("Magneto", 1, 24)); // NOI18N
        botonSalas.setText("Salas");
        botonSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalasActionPerformed(evt);
            }
        });

        botonEmpleado.setFont(new java.awt.Font("Magneto", 1, 24)); // NOI18N
        botonEmpleado.setText("Empleados");
        botonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadoActionPerformed(evt);
            }
        });

        botonHistorico.setFont(new java.awt.Font("Magneto", 1, 24)); // NOI18N
        botonHistorico.setText("Registros");
        botonHistorico.setActionCommand("Empleados");
        botonHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistoricoActionPerformed(evt);
            }
        });

        botonPelis.setFont(new java.awt.Font("Magneto", 1, 24)); // NOI18N
        botonPelis.setText("Películas");
        botonPelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPelisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonPelis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(botonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPelis, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(botonHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dato y metadatos"));
        jPanel2.setToolTipText("");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Fecha apertura: ");

        jLabel4.setText("Dirección:");

        labelNombre.setText("jLabel5");

        labelFecha.setText("jLabel5");

        labelDireccion.setText("jLabel5");

        botonMetadato.setText("Metadatos");
        botonMetadato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMetadatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMetadato)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(botonMetadato)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ponerDatosExtras(String tipoBBDD) {
        switch (tipoBBDD) {
            case "sqlite":
                labelNombre.setText("Cines Jindaka");
                labelDireccion.setText("Calle falsa 123");
                labelFecha.setText("Martes, 21 de Noviembre de 2015");
                break;
            case "mysql":
                labelNombre.setText("Cines Cajoinda");
                labelDireccion.setText("Calle cierta 123");
                labelFecha.setText("Miércoles, 22 de Noviembre de 2015");
                break;
            default:
                break;
        }
    }

    private void botonSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalasActionPerformed
        if (ventanaAMB == null) {
            ventanaAMB = new SQL.Ventanas.AMB();
            ventanaAMB.ventanaEleccion = this;// Pasarle este ventanaEleccion
        }
        ventanaAMB.salaFunciones = this.salaFunciones;//pasarle funciones
        salaFunciones.abrirVentanaSalas(ventanaAMB);//pasarlo a la clase de las funciones de esa sala
        ventanaAMB.setVisible(true);//ver ventana
        ventanaAMB.setSoyMySql(soyMySql);//pasarle tipo de base de datos
        this.setEnabled(false);//deshabilitar esta para no abrir de mas

        System.out.println(ventanaAMB.isSoyMySql());
    }//GEN-LAST:event_botonSalasActionPerformed

    private void botonPelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPelisActionPerformed
        if (ventanaAMB == null) {
            ventanaAMB = new SQL.Ventanas.AMB();
            ventanaAMB.ventanaEleccion = this;// Pasarle este ventanaEleccion
        }
        ventanaAMB.peliculaFunciones = this.peliculaFunciones;//pasarle funciones
        peliculaFunciones.abrirVentanaPelis(ventanaAMB);//pasarlo a la clase de las funciones de esa sala
        ventanaAMB.setVisible(true);//ver ventana
        ventanaAMB.setSoyMySql(soyMySql);//pasarle tipo de base de datos
        this.setEnabled(false);//deshabilitar esta para no abrir de mas

        System.out.println(ventanaAMB.isSoyMySql());
    }//GEN-LAST:event_botonPelisActionPerformed

    private void botonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadoActionPerformed
        if (ventanaAMB == null) {
            ventanaAMB = new SQL.Ventanas.AMB();
            ventanaAMB.ventanaEleccion = this;// Pasarle este ventanaEleccion
        }
        ventanaAMB.empleadoFunciones = this.empleadoFunciones;//pasarle funciones
        empleadoFunciones.abrirVentanaEmpleados(ventanaAMB);//pasarlo a la clase de las funciones de esa sala
        ventanaAMB.setVisible(true);//ver ventana
        ventanaAMB.setSoyMySql(soyMySql);//pasarle tipo de base de datos
        this.setEnabled(false);//deshabilitar esta para no abrir de mas        

        System.out.println(ventanaAMB.isSoyMySql());

    }//GEN-LAST:event_botonEmpleadoActionPerformed

    private void botonHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistoricoActionPerformed
        if (ventanaHistorico == null) {
            ventanaHistorico = new SQL.Ventanas.Historico();
            ventanaHistorico.ventanaEleccion = this;// Pasarle este ventanaEleccion

            ventanaHistorico.setSoyMySql(soyMySql);// pasarle si es mysql o no para rellenar los combos
        }
        ventanaHistorico.historicoFunciones = this.historicoFunciones;//pasarle funciones
        try {
            historicoFunciones.abrirVentanaHistorico(ventanaHistorico);//pasarlo a la clase de las funciones de esa sala
        } catch (IOException ex) {
            Logger.getLogger(Eleccion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Eleccion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Eleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaHistorico.setVisible(true);//ver ventana
        ventanaHistorico.setSoyMySql(soyMySql);//pasarle tipo de base de datos
        this.setEnabled(false);//deshabilitar esta para no abrir de mas        
    }//GEN-LAST:event_botonHistoricoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //volver a atras, dejando la anterior disponible OJO que se usa dispose por si se quiere acceder a otro local (bbdd)
        ventanaMain.setEnabled(true);
        ventanaMain.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void botonMetadatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMetadatoActionPerformed
        if (ventanaMetadatos == null) {
            ventanaMetadatos = new Metadatos();
            ventanaMetadatos.ventanaEleccion = this;// Pasarle este ventanaEleccion
        }
        ventanaMetadatos.soyMySql = this.soyMySql;
        ventanaMetadatos.setVisible(true);
        this.setEnabled(false);//deshabilitar esta para no abrir de mas        
        ventanaMetadatos.sacarMetadatos();


    }//GEN-LAST:event_botonMetadatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eleccion().setVisible(true);
            }
        });
    }

    /**
     *
     * @return devuelve true o false en funcion de sql o mysql
     */
    public boolean isSoyMySql() {
        return soyMySql;
    }

    /**
     *
     * @param soyMySql meter true o false en funcion de sql o mysql
     */
    public void setSoyMySql(boolean soyMySql) {
        this.soyMySql = soyMySql;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botonEmpleado;
    public static javax.swing.JButton botonHistorico;
    private javax.swing.JButton botonMetadato;
    public static javax.swing.JButton botonPelis;
    public static javax.swing.JButton botonSalas;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel labelDireccion;
    public static javax.swing.JLabel labelFecha;
    public static javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
